language: dart
sudo: false

dart:
- stable

dart_task:
- test: --platform vm
- dartanalyzer
- dartfmt: sdk

notifications:
  email:
    recipients:
      - julemand101@archlinux.dk
    on_success: always
    on_failure: always
