name: AdventOfCode2017
description: Solutions for Advent of Code 2017.
version: 0.0.1
homepage: http://www.archlinux.dk
author: Jacob Bang <julemand101@archlinux.dk>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  collection: "^1.14.11"
  tuple: "^1.0.2"

dev_dependencies:
  test: "^1.3.0"
